services:
- type: web
  name: dating_app
  env: python
  plan: starter
  buildCommand: ./build.sh
  startCommand: gunicorn dating_app.wsgi:application
  autoDeploy: false
  envVars:
    - key: WEB_CONCURRENCY
      value: 4
    - key: DATABASE_URL
      fromDatabase:
        name: dating_app
        property: connectionString
    - key: DJANGO_SECRET_KEY
      generateValue: true
    - key: DJANGO_ADMIN_URL
      generateValue: true
    - key: DJANGO_SETTINGS_MODULE
      value: dating_app.settings.production

